CREATE DATABASE Pessoas;

USE Pessoas;

CREATE TABLE CNH
(
	idCNH INT PRIMARY KEY IDENTITY
	,Registro VARCHAR (14)
);

CREATE TABLE Pessoa
(
 idPessoa INT PRIMARY KEY IDENTITY,
 Nome	  VARCHAR (200) NOT NULL,
 idCNH	  BIGINT NOT NULL,
 Endereco VARCHAR (200) NOT NULL,
);

CREATE TABLE Emails
( 
 idEmail INT PRIMARY KEY IDENTITY,
 idPessoa INT FOREIGN KEY REFERENCES Pessoa(idPessoa),
 Endereco_de_email VARCHAR (255) NOT NULL,
);

CREATE TABLE Telefones
(
 idTelefone INT PRIMARY KEY IDENTITY,
 idPessoa  INT FOREIGN KEY REFERENCES Pessoa(idPessoa),
 Numero VARCHAR(200) NOT NULL
);